name = "tiny-ai-worker-todo-example"
main = "src/index.ts"
compatibility_date = "2023-04-07"

kv_namespaces = [
  { binding = "template-EXAMPLE_TODOS-31a5bca3-6413-4fd7-aa4b-2cd349e55ae7", id = "291a1ac047734e03a1ca0b70b8bc836d" }
]
